export const TIMING = {
  LOADING_MS: 2600,
  SCAN_MS: 4500,
  RESULT_MS: 5000,
  TRANSITION_MS: 500,
};

export const STORAGE = {
  LOG_KEY: 'checkin007.log.v1',
  ROSTER_KEY: 'checkin007.roster.v1',
  AUDIO_KEY: 'checkin007.audio.v1',
};

export const AUDIO = {
  SCAN_BLIP_DEFAULT_ENABLED: false,
  SCAN_BLIP_GAIN: 0.045,
  SCAN_BLIP_START_HZ: 880,
  SCAN_BLIP_END_HZ: 1320,
  SCAN_BLIP_DURATION_MS: 90,
  SCAN_BLIP_RELEASE_SECONDS: 0.035,
};

export const ADMIN = {
  HOLD_MS: 2000,
  HITZONE_PX: 72,
};

export const ROSTER = {
  SEARCH_DEBOUNCE_MS: 120,
  VIRTUALIZE_THRESHOLD: 500,
  VIRTUAL_ROW_HEIGHT_PX: 66,
  VIRTUAL_VISIBLE_ROW_HEIGHT_PX: 58,
  VIRTUAL_OVERSCAN_ROWS: 6,
  VIRTUAL_MIN_VIEWPORT_PX: 360,
};

export const REDUCED = {
  LOADING_MS: 900,
  SCAN_MS: 2500,
  RESULT_MS: 4000,
  TRANSITION_MS: 150,
};
